from base import IRCBot

bot = IRCBot()
bot.setServer('irc.quakenet.org')
bot.setPort(6667)
bot.setRealName('Thor22')
bot.setNick('Thor22')
bot.setCall('$')
bot.setDebugLevel(2)
print(bot.getServer())
print(bot.getPort())
print(bot.getRealName())
print(bot.getNick())
print(bot.getCall())
print(bot.getDebugLevel())
bot.start()